# Generated by Django 6.0.3 on 2026-04-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={},
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='created_at',
        ),
    ]
