# Generated by Django 6.0.3 on 2026-04-02 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_alter_medicine_options_remove_medicine_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='frequency_per_day',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='timing',
        ),
        migrations.AddField(
            model_name='medicine',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='frequency_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10),
        ),
        migrations.CreateModel(
            name='MedicineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medicines.medicine')),
            ],
        ),
    ]
