# Generated by Django 6.0.3 on 2026-04-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_remove_medicine_frequency_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineschedule',
            name='last_taken_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
